### ISSUE TITLE
Recycle scroller item's view position issue (translateY invalid)

### ISSUE THREAD

**Issue by denispriler** [Akryum/vue-virtual-scroller#196]
When scroller updates and counting items pisition it becomes invalid so it's view translateY makes them to be positioned in wrong place.
![image](https://user-images.githubusercontent.com/29511426/56736622-5108b000-6771-11e9-981a-187df9a67f1a.png)
![image](https://user-images.githubusercontent.com/29511426/56736668-6e3d7e80-6771-11e9-90b5-dd2645d80e34.png)
As i understand the view's position shold be updated after 1175 line but it is not.
Because of this there are a lot of blank place between first and second list elements.

**Comment by schrieveslaach** [comment]
I had the same problem but I solved this by setting some class:

```css
   .vue-recycle-scroller__item-wrapper {
      position: relative;
   }
   .vue-recycle-scroller__item-view {
      position: absolute;
   }
```

Is it possible that `vue-virtual-scroller` has to add these CSS classes?
