### ISSUE TITLE
Example of fixed table header with recycle-list

### ISSUE THREAD

**Issue by thomasrosdahl** [Akryum/vue-virtual-scroller#66]
Could you please provide an example of this? Should I use slots? If so there only seems to be an `after-container` slot with `recycle-list`. So not sure how to get something like a `position: sticky` element in there.

Thanks,

Thomas

**Comment by Akryum** [comment]
I guess a sticky position on an element in the before or after-container slots would do the trick.

**Comment by gambolputty** [comment]
I tested this with Dynamic Scroller, setting an element inside the before slot to `position: sticky` and it didn't work. Setting the slot container instead to `position: sticky` worked (and adding a `z-index` property).

**Comment by luciano-work** [comment]
I'm trying to add a sticky header before RecycleScroller, but after some scroll the header disappears:
```vue
<!-- This need to be Stciky -->
<div class="sticky top-0 z-10 px-8 py-4 dark:bg-red-800 sm:px-8">
    <div class="ellipsis-one-line flex items-center gap-4 text-xs uppercase text-gray-400 dark:text-night-400">
      <div class="w-8 flex-shrink-0 text-right">#</div>
      <div class="w-full">Título</div>
      <div class="hidden w-full md:block">Álbum</div>
      <div class="flex w-10 justify-end"></div>
      <div class="flex w-28 justify-end">
        <inline-svg src="icons/clock-hour-3.svg" class="stroke-1.5 h-4 w-4" />
      </div>
      <div class="flex w-10 justify-end"></div>
      <div class="w-10"></div>
    </div>
  </div>

  <RecycleScroller
    :pageMode="true"
    class="content-scroll px-4 pb-4 sm:px-8"
    :items="songs"
    :item-size="65"
    key-field="id"
    v-slot="{ item, index }">
    <SongListItem :song="item" :index="index + 1" @play="play" />
  </RecycleScroller>
```

https://user-images.githubusercontent.com/12519008/234578411-9aef3483-36cf-481a-bdfd-6edbc9778374.mp4

Why this happens?

**Comment by tastytea-github** [comment]
> I tested this with Dynamic Scroller, setting an element inside the before slot to `position: sticky` and it didn't work. Setting the slot container instead to `position: sticky` worked (and adding a `z-index` property).

I have the similar issue https://github.com/Akryum/vue-virtual-scroller/issues/811 but I need to declare sticky elements inside the default slot. It doesn't work due to `overflow: hidden` on a DynamicScroller wrapper element.

**Comment by EmilyRagan** [comment]
> I tested this with Dynamic Scroller, setting an element inside the before slot to `position: sticky` and it didn't work. Setting the slot container instead to `position: sticky` worked (and adding a `z-index` property).

This comment is for people looking to do this, but are lost on the actual practical "how":
In order to do this, I added a class name on my `<DynamicScroller class="dynamic-scroller" />`, and then had to use non-scoped styling to grab the slots:
```scss
<style lang="scss">
// Sneaky way to get the footer to stick at the bottom of the list
// Set all div.vue-recycle-scroller__slot to stick to the bottom, but then override the first-child (header) to stick to the top
.dynamic-scroller > div.vue-recycle-scroller__slot {
  position: sticky;
  bottom: 0;
  z-index: 1;
}
.dynamic-scroller > div.vue-recycle-scroller__slot:first-child {
  position: sticky;
  top: 0;
  z-index: 1;
}
</style>
```
