### ISSUE TITLE
Disabling child transitions

### ISSUE THREAD

**Issue by murrant** [Akryum/vue-virtual-scroller#70]
I have a few elements in my scrolled items that have animations using transitions and when the virtual scroller swaps out the items, it triggers the animations.

I've created the following css
```css
    .no-transition {
        transition: none !important
    }
```

To skip the transitions, I need to add the `no-transition` class to the element before the data is swapped and remove it after the data is swapped.

Is there any way to do this now or would code changes need to be made?
